In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

# Lineer Denklem

$ Ax = b $ sistemi için.

$ A  = \begin{bmatrix} 1 & 2 & 3 \cr 3 & 4 & -3 \cr 9 & -7 & 2 \end{bmatrix} $


In [4]:
A = np.array([[1,2,3], [3,4,-3], [9,-7,2] ])

In [5]:
print("A = \n", A)

A = 
 [[ 1  2  3]
 [ 3  4 -3]
 [ 9 -7  2]]


In [6]:
from IPython.display import display, Math

def print_matrix(array):
    matrix = ''
    for row in array:
        try:
            for number in row:
                matrix += f'{number:.4f}&'
        except TypeError:
            matrix += f'{row}&'
        matrix = matrix[:-1] + r'\\'
    display(Math(r'\begin{bmatrix*}[r]'+matrix+r'\end{bmatrix*}'))

In [7]:
print_matrix(A)

<IPython.core.display.Math object>